name: edgesync
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  path: ^1.9.0
  gal: ^2.3.0
  video_player: ^2.8.6
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_commons: ^0.11.0
  # For noise injection ML models
  tflite_flutter: ^0.10.4
  image: ^4.2.0
  # For Windows desktop file picker
  file_picker: ^8.0.7
  # For text recognition (OCR)
  google_mlkit_text_recognition: ^0.15.0
  # For HTTP requests to Groq API
  http: ^1.2.1
  # For JSON handling
  convert: ^3.1.1
  # For URL launcher (calendar, contacts, etc.)
  url_launcher: ^6.2.5
  # For local storage
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  flutter_contacts: ^1.1.7
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.3
  android_intent_plus: ^5.2.0
  speech_to_text: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/Icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/models/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
